import os

structure = {
    "flight_sim": [
        "main.py",
        "aircraft.py",
        "controls.py",
        "hud.py",
        "config.py"
    ]
}

for folder, files in structure.items():
    os.makedirs(folder, exist_ok=True)
    for file in files:
        path = os.path.join(folder, file)
        with open(path, "w") as f:
            f.write(f"# {file} - autogenerated\n")

