# aircraft.py - autogenerated
import math

class Aircraft:
    def __init__(self):
        self.x, self.y = 0.0, 1000.0      # Position (m)
        self.vx, self.vy = 0.0, 0.0       # Velocity (m/s)
        self.angle = 0.0                  # Pitch angle (deg)
        self.thrust = 0.0                 # Engine power (0–1)
        self.mass = 500.0                 # kg

    def update(self, dt):
        g = 9.81
        rho = 1.225
        wing_area = 16.2

        lift = 0.5 * rho * (self.vy ** 2) * wing_area * math.cos(math.radians(self.angle))
        drag = 0.5 * rho * (self.vx ** 2) * wing_area * 0.05
        thrust_force = self.thrust * 5000  # N

        ax = (thrust_force - drag) / self.mass
        ay = (lift - self.mass * g) / self.mass

        self.vx += ax * dt
        self.vy += ay * dt
        self.x += self.vx * dt
        self.y += self.vy * dt