# config.py - autogenerated
# Flight simulation configuration
WINDOW_TITLE = "Flight Sim"
BACKGROUND_COLOR = (0.5, 0.7, 1.0)

DEFAULT_SPEED = 10.0
MAX_PITCH = 45
MIN_PITCH = -45

CAMERA_START_POS = (0, -50, 15)
HUD_FONT = "arial.ttf"  # Use default system font or load from assets
HUD_SCALE = 0.07