def handle_keys(event, aircraft):
    key = event.keysym
    if key == "Up":
        aircraft.thrust = min(1.0, aircraft.thrust + 0.05)
    elif key == "Down":
        aircraft.thrust = max(0.0, aircraft.thrust - 0.05)
    elif key == "Left":
        aircraft.angle = max(-30, aircraft.angle - 2)
    elif key == "Right":
        aircraft.angle = min(30, aircraft.angle + 2)
# controls.py - autogenerated
