# hud.py - autogenerated
#Dynamic HUD Overlay
from panda3d.core import TextNode, NodePath, Vec3
from direct.gui.OnscreenText import OnscreenText
import config

class HUD:
    def __init__(self):
        self.alt_text = self._make_text(pos=(-1.3, 0.9), label="Altitude: 0")
        self.pitch_text = self._make_text(pos=(-1.3, 0.85), label="Pitch: 0°")
        self.speed_text = self._make_text(pos=(-1.3, 0.80), label="Speed: 0")

    def _make_text(self, pos, label):
        return OnscreenText(
            text=label,
            pos=pos,
            scale=config.HUD_SCALE,
            fg=(1, 1, 1, 1),
            align=TextNode.ALeft,
            font=None,  # Default font
            mayChange=True
        )

    def update(self, altitude, pitch, speed):
        self.alt_text.setText(f"Altitude: {altitude:.1f}")
        self.pitch_text.setText(f"Pitch: {pitch:.1f}°")
        self.speed_text.setText(f"Speed: {speed:.1f}")